// @vitest-environment node
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import { beforeAll, afterAll, it, expect } from 'vitest';
let db;
beforeAll(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create schema auth;
    create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
    create table profiles(id uuid,is_admin boolean); insert into profiles values(auth.uid(),true);
    create table matches(id text primary key,season text,date date,opponent text,status text);
    create table gameweeks(id bigint generated by default as identity,name text,opponent text,date date,deadline timestamptz,match_id text,stats_file text,season_id text);
    create table fantasy_season_settings(season_id text,market_ready boolean); insert into fantasy_season_settings values('2026-2027',true);
    create function public.ensure_gazalbet_markets(bigint) returns void language plpgsql as $$begin raise exception 'market failure'; end$$;`);
  await db.exec(await readFile('supabase/migrations/20261008061459_unified_match_scheduling.sql','utf8'));
});
afterAll(async () => { await db.close(); });
const args = (id, fantasy = false, markets = false) => `select schedule_match('${id}','2026-2027','2026-10-10','Rival',${fantasy},'J1',now()+interval '1 day',${markets})`;
it('schedules the same match identity with an optional Fantasy round',async()=>{
  const { rows } = await db.query(args('linked',true));
  expect(rows[0].schedule_match.gameweek.match_id).toBe('linked');
  expect((await db.query("select status,is_scheduled from matches where id='linked'")).rows[0]).toEqual({status:'draft',is_scheduled:true});
});
it('rejects duplicate identities',async()=>{await expect(db.query(args('linked'))).rejects.toThrow(/ya está/);});
it('rolls back the match and gameweek when market generation fails',async()=>{
  await expect(db.query(args('failed',true,true))).rejects.toThrow('market failure');
  expect((await db.query("select * from matches where id='failed'")).rows).toHaveLength(0);
  expect((await db.query("select * from gameweeks where match_id='failed'")).rows).toHaveLength(0);
});
it('rejects non-admin callers',async()=>{
  await db.exec('update profiles set is_admin=false');
  await expect(db.query(args('forbidden'))).rejects.toThrow(/administradores/);
  await db.exec('update profiles set is_admin=true');
});
