-- Gazalbide Stats: core historical/live-ready statistics schema.
-- Safe to run alongside the existing Fantasy tables.

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  number text not null unique,
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id text primary key,
  season text not null default '2025-26',
  date date not null,
  opponent text not null,
  source_file text,
  source_sheet text,
  gazal_pts integer not null default 0,
  opp_pts integer not null default 0,
  q_pf integer[] not null default '{}',
  q_pa integer[] not null default '{}',
  result text check (result in ('W', 'L', 'D')),
  status text not null default 'published'
    check (status in ('draft', 'live', 'finished', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_match_stats (
  match_id text not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  sort_order integer not null default 0,
  min_seconds integer not null default 0,
  min_str text not null default '00:00',
  pts integer not null default 0,
  two_pm integer not null default 0,
  two_pa integer not null default 0,
  three_pm integer not null default 0,
  three_pa integer not null default 0,
  fgm integer not null default 0,
  fga integer not null default 0,
  ftm integer not null default 0,
  fta integer not null default 0,
  oreb integer not null default 0,
  dreb integer not null default 0,
  reb integer not null default 0,
  ast integer not null default 0,
  tov integer not null default 0,
  stl integer not null default 0,
  blk integer not null default 0,
  pf integer not null default 0,
  pfd integer not null default 0,
  pir integer not null default 0,
  eff integer not null default 0,
  plus_minus integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (match_id, player_id)
);

create index if not exists matches_date_idx
  on public.matches(date desc);

create index if not exists player_match_stats_player_idx
  on public.player_match_stats(player_id);

create index if not exists player_match_stats_match_sort_idx
  on public.player_match_stats(match_id, sort_order);

-- Reuse the current profiles.is_admin flag instead of introducing another role.
create or replace function public.is_gazal_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select p.is_admin from public.profiles p where p.id = auth.uid()),
    false
  );
$$;

grant execute on function public.is_gazal_admin() to authenticated;

alter table public.players enable row level security;
alter table public.matches enable row level security;
alter table public.player_match_stats enable row level security;

-- Public/statistical data can be read by anyone, as it is already public on GitHub Pages.
drop policy if exists "stats_players_public_read" on public.players;
create policy "stats_players_public_read"
  on public.players for select
  using (true);

drop policy if exists "stats_matches_public_read" on public.matches;
create policy "stats_matches_public_read"
  on public.matches for select
  using (status = 'published' or public.is_gazal_admin());

drop policy if exists "stats_player_match_public_read" on public.player_match_stats;
create policy "stats_player_match_public_read"
  on public.player_match_stats for select
  using (
    exists (
      select 1
      from public.matches m
      where m.id = player_match_stats.match_id
        and (m.status = 'published' or public.is_gazal_admin())
    )
  );

-- The existing admin role will own all management operations.
drop policy if exists "stats_players_admin_insert" on public.players;
create policy "stats_players_admin_insert"
  on public.players for insert to authenticated
  with check (public.is_gazal_admin());

drop policy if exists "stats_players_admin_update" on public.players;
create policy "stats_players_admin_update"
  on public.players for update to authenticated
  using (public.is_gazal_admin())
  with check (public.is_gazal_admin());

drop policy if exists "stats_players_admin_delete" on public.players;
create policy "stats_players_admin_delete"
  on public.players for delete to authenticated
  using (public.is_gazal_admin());

drop policy if exists "stats_matches_admin_all" on public.matches;
create policy "stats_matches_admin_all"
  on public.matches for all to authenticated
  using (public.is_gazal_admin())
  with check (public.is_gazal_admin());

drop policy if exists "stats_player_match_admin_all" on public.player_match_stats;
create policy "stats_player_match_admin_all"
  on public.player_match_stats for all to authenticated
  using (public.is_gazal_admin())
  with check (public.is_gazal_admin());
