-- Gazalbide Stats: Live Stats core model.
-- Detailed stats are recorded only for Gazalbide players.
-- The opponent is intentionally aggregated: only points and team fouls are tracked.

alter table public.matches
  add column if not exists gazal_side text not null default 'home'
  check (gazal_side in ('home', 'away'));

create table if not exists public.game_roster (
  match_id text not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  jersey_number text not null,
  player_name text not null,
  sort_order integer not null default 0,
  is_starter boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (match_id, player_id)
);

create table if not exists public.live_game_state (
  match_id text primary key references public.matches(id) on delete cascade,
  period smallint not null default 1 check (period >= 1),
  clock_ms integer not null default 600000 check (clock_ms >= 0),
  clock_running boolean not null default false,
  period_duration_ms integer not null default 600000 check (period_duration_ms > 0),
  overtime_duration_ms integer not null default 300000 check (overtime_duration_ms > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_events (
  id uuid primary key,
  match_id text not null references public.matches(id) on delete cascade,
  server_sequence bigint generated by default as identity unique,
  client_id uuid not null,
  client_sequence bigint not null,
  client_created_at timestamptz not null,
  period smallint not null check (period >= 1),
  clock_ms integer not null check (clock_ms >= 0),
  subject text not null check (subject in ('gazalbide', 'opponent', 'system')),
  event_type text not null check (event_type in (
    'FT_MADE', 'FT_MISSED', 'TWO_MADE', 'TWO_MISSED', 'THREE_MADE', 'THREE_MISSED',
    'OREB', 'DREB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PFD', 'SUB_IN', 'SUB_OUT',
    'OPP_SCORE_1', 'OPP_SCORE_2', 'OPP_SCORE_3', 'OPP_TEAM_FOUL',
    'PERIOD_START', 'PERIOD_END', 'CLOCK_SET'
  )),
  player_id bigint references public.players(id) on delete restrict,
  related_player_id bigint references public.players(id) on delete restrict,
  action_group_id uuid,
  is_void boolean not null default false,
  voided_at timestamptz,
  void_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, client_id, client_sequence),
  constraint game_events_subject_player_check check (
    (subject = 'gazalbide' and player_id is not null)
    or (subject in ('opponent', 'system') and player_id is null)
  ),
  constraint game_events_opponent_types_check check (
    subject <> 'opponent' or event_type in ('OPP_SCORE_1', 'OPP_SCORE_2', 'OPP_SCORE_3', 'OPP_TEAM_FOUL')
  ),
  constraint game_events_system_types_check check (
    subject <> 'system' or event_type in ('PERIOD_START', 'PERIOD_END', 'CLOCK_SET')
  ),
  constraint game_events_gazalbide_types_check check (
    subject <> 'gazalbide' or event_type in (
      'FT_MADE', 'FT_MISSED', 'TWO_MADE', 'TWO_MISSED', 'THREE_MADE', 'THREE_MISSED',
      'OREB', 'DREB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PFD', 'SUB_IN', 'SUB_OUT'
    )
  )
);

create index if not exists game_events_match_server_order_idx on public.game_events(match_id, server_sequence);
create index if not exists game_events_match_client_order_idx on public.game_events(match_id, client_id, client_sequence);
create index if not exists game_events_match_period_clock_idx on public.game_events(match_id, period, clock_ms desc);
create index if not exists game_events_player_idx on public.game_events(player_id) where player_id is not null;
create index if not exists game_events_live_feed_idx on public.game_events(match_id, is_void, server_sequence desc);

alter table public.game_roster enable row level security;
alter table public.live_game_state enable row level security;
alter table public.game_events enable row level security;

drop policy if exists "live_roster_read" on public.game_roster;
create policy "live_roster_read" on public.game_roster for select using (
  exists (select 1 from public.matches m where m.id = game_roster.match_id and (m.status in ('live', 'published') or public.is_gazal_admin()))
);

drop policy if exists "live_state_read" on public.live_game_state;
create policy "live_state_read" on public.live_game_state for select using (
  exists (select 1 from public.matches m where m.id = live_game_state.match_id and (m.status in ('live', 'published') or public.is_gazal_admin()))
);

drop policy if exists "live_events_read" on public.game_events;
create policy "live_events_read" on public.game_events for select using (
  exists (select 1 from public.matches m where m.id = game_events.match_id and (m.status in ('live', 'published') or public.is_gazal_admin()))
);

drop policy if exists "live_roster_admin_all" on public.game_roster;
create policy "live_roster_admin_all" on public.game_roster for all to authenticated using (public.is_gazal_admin()) with check (public.is_gazal_admin());

drop policy if exists "live_state_admin_all" on public.live_game_state;
create policy "live_state_admin_all" on public.live_game_state for all to authenticated using (public.is_gazal_admin()) with check (public.is_gazal_admin());

drop policy if exists "live_events_admin_insert" on public.game_events;
create policy "live_events_admin_insert" on public.game_events for insert to authenticated with check (public.is_gazal_admin());

drop policy if exists "live_events_admin_update" on public.game_events;
create policy "live_events_admin_update" on public.game_events for update to authenticated using (public.is_gazal_admin()) with check (public.is_gazal_admin());
