-- Generate/provision VAPID from the Edge Function itself so the private key
-- never appears in GitHub or client code. Only service_role can initialize/read it.

create or replace function public.notification_initialize_vapid(
  p_public_key text,
  p_private_key text
)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare v_id uuid;
begin
  if coalesce(length(p_public_key),0)<40 or coalesce(length(p_private_key),0)<20 then
    raise exception 'Invalid VAPID key material';
  end if;

  select id into v_id
  from vault.secrets
  where name='gazalbide_vapid_private'
  order by created_at desc
  limit 1;

  if v_id is null then
    perform vault.create_secret(
      p_private_key,
      'gazalbide_vapid_private',
      'Gazalbide PWA VAPID private key generated by push-dispatch',
      null
    );
  else
    perform vault.update_secret(
      v_id,
      p_private_key,
      'gazalbide_vapid_private',
      'Gazalbide PWA VAPID private key generated by push-dispatch',
      null
    );
  end if;

  update public.notification_server_config
  set vapid_public_key=p_public_key, updated_at=now()
  where singleton=true;
end;
$$;
revoke all on function public.notification_initialize_vapid(text,text) from public, anon, authenticated;
grant execute on function public.notification_initialize_vapid(text,text) to service_role;

drop function if exists public.notification_push_server_secrets(text);
create or replace function public.notification_push_server_secrets()
returns jsonb
language plpgsql
security definer
set search_path = public, vault
as $$
declare cfg public.notification_server_config%rowtype; v_private text;
begin
  select * into cfg from public.notification_server_config where singleton=true;
  select decrypted_secret into v_private
  from vault.decrypted_secrets
  where name='gazalbide_vapid_private'
  order by created_at desc
  limit 1;

  if v_private is null then return null; end if;
  return jsonb_build_object(
    'vapidPublicKey',cfg.vapid_public_key,
    'vapidPrivateKey',v_private,
    'vapidSubject',cfg.vapid_subject
  );
end;
$$;
revoke all on function public.notification_push_server_secrets() from public, anon, authenticated;
grant execute on function public.notification_push_server_secrets() to service_role;

create or replace function public.dispatch_push_notifications()
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare cfg public.notification_server_config%rowtype; v_request_id bigint;
begin
  select * into cfg from public.notification_server_config where singleton=true;
  if cfg.edge_function_url is null then return null; end if;

  select net.http_post(
    url := cfg.edge_function_url,
    headers := '{"Content-Type":"application/json"}'::jsonb,
    body := '{"limit":100}'::jsonb,
    timeout_milliseconds := 10000
  ) into v_request_id;
  return v_request_id;
end;
$$;
revoke all on function public.dispatch_push_notifications() from public, anon, authenticated;
