-- Gazalbide Stats: per-gameweek Fantasy economy with carry-over and audit ledger.
-- The authoritative budget moves from fantasy_teams.cervezas to one economy row per
-- Fantasy team and gameweek. fantasy_teams.cervezas remains as a compatibility cache.

alter table public.fantasy_season_settings
  add column if not exists max_carry integer not null default 20;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fantasy_season_settings_max_carry_check'
      and conrelid = 'public.fantasy_season_settings'::regclass
  ) then
    alter table public.fantasy_season_settings
      add constraint fantasy_season_settings_max_carry_check
      check (max_carry >= 0);
  end if;
end
$$;

create table if not exists public.fantasy_gameweek_economy (
  fantasy_team_id uuid not null references public.fantasy_teams(id) on delete cascade,
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  base_budget integer not null check (base_budget > 0),
  carry_in integer not null default 0 check (carry_in >= 0),
  available_budget integer generated always as (base_budget + carry_in) stored,
  lineup_cost integer check (lineup_cost is null or lineup_cost >= 0),
  valid_lineup boolean not null default false,
  savings_generated integer not null default 0 check (savings_generated >= 0),
  carry_out integer not null default 0 check (carry_out >= 0),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (fantasy_team_id, gameweek_id)
);

create index if not exists fantasy_gameweek_economy_gameweek_idx
  on public.fantasy_gameweek_economy(gameweek_id);

create table if not exists public.fantasy_economy_ledger (
  id bigint generated by default as identity primary key,
  fantasy_team_id uuid not null references public.fantasy_teams(id) on delete cascade,
  gameweek_id bigint references public.gameweeks(id) on delete cascade,
  entry_type text not null check (
    entry_type in (
      'base_budget',
      'carry_in',
      'savings',
      'savings_cap',
      'le_gazal_bet',
      'le_gazal_payout',
      'prize',
      'loss',
      'admin_adjustment'
    )
  ),
  event_key text not null,
  amount integer not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (fantasy_team_id, gameweek_id, event_key)
);

create index if not exists fantasy_economy_ledger_team_created_idx
  on public.fantasy_economy_ledger(fantasy_team_id, created_at desc);

create index if not exists fantasy_economy_ledger_gameweek_idx
  on public.fantasy_economy_ledger(gameweek_id);

alter table public.fantasy_gameweek_economy enable row level security;
alter table public.fantasy_economy_ledger enable row level security;

revoke all on public.fantasy_gameweek_economy from anon;
revoke all on public.fantasy_economy_ledger from anon;
grant select, insert, update, delete on public.fantasy_gameweek_economy to authenticated;
grant select, insert, update, delete on public.fantasy_economy_ledger to authenticated;
grant usage, select on sequence public.fantasy_economy_ledger_id_seq to authenticated;

drop policy if exists "fantasy_gameweek_economy_own_read"
  on public.fantasy_gameweek_economy;
create policy "fantasy_gameweek_economy_own_read"
  on public.fantasy_gameweek_economy
  for select to authenticated
  using (
    exists (
      select 1
      from public.fantasy_teams ft
      where ft.id = fantasy_gameweek_economy.fantasy_team_id
        and ft.user_id = (select auth.uid())
    )
  );

drop policy if exists "fantasy_gameweek_economy_admin_all"
  on public.fantasy_gameweek_economy;
create policy "fantasy_gameweek_economy_admin_all"
  on public.fantasy_gameweek_economy
  for all to authenticated
  using ((select public.is_gazal_admin()))
  with check ((select public.is_gazal_admin()));

drop policy if exists "fantasy_economy_ledger_own_read"
  on public.fantasy_economy_ledger;
create policy "fantasy_economy_ledger_own_read"
  on public.fantasy_economy_ledger
  for select to authenticated
  using (
    exists (
      select 1
      from public.fantasy_teams ft
      where ft.id = fantasy_economy_ledger.fantasy_team_id
        and ft.user_id = (select auth.uid())
    )
  );

drop policy if exists "fantasy_economy_ledger_admin_all"
  on public.fantasy_economy_ledger;
create policy "fantasy_economy_ledger_admin_all"
  on public.fantasy_economy_ledger
  for all to authenticated
  using ((select public.is_gazal_admin()))
  with check ((select public.is_gazal_admin()));

create or replace function public.finalize_fantasy_gameweek_economy(
  p_gameweek_id bigint
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_gameweek public.gameweeks%rowtype;
  v_max_carry integer := 20;
  v_row record;
  v_matched_players integer;
  v_distinct_players integer;
  v_priced_players integer;
  v_lineup_cost integer;
  v_has_captain boolean;
  v_has_coach boolean;
  v_valid boolean;
  v_savings integer;
  v_carry_out integer;
  v_finalized_count integer := 0;
  v_invalid_count integer := 0;
begin
  if auth.uid() is null or not public.is_gazal_admin() then
    raise exception 'Admin permissions required';
  end if;

  select *
    into v_gameweek
  from public.gameweeks
  where id = p_gameweek_id;

  if not found then
    raise exception 'Gameweek % not found', p_gameweek_id;
  end if;

  if v_gameweek.deadline > now() then
    raise exception 'Cannot finalize Fantasy economy before the gameweek deadline';
  end if;

  select coalesce(fss.max_carry, 20)
    into v_max_carry
  from public.fantasy_season_settings fss
  where fss.season_id = v_gameweek.season_id;

  v_max_carry := coalesce(v_max_carry, 20);

  insert into public.fantasy_gameweek_economy (
    fantasy_team_id,
    gameweek_id,
    base_budget,
    carry_in
  )
  select
    ft.id,
    v_gameweek.id,
    v_gameweek.base_budget,
    0
  from public.fantasy_teams ft
  where ft.season_id = v_gameweek.season_id
  on conflict (fantasy_team_id, gameweek_id) do nothing;

  for v_row in
    select
      e.fantasy_team_id,
      e.base_budget,
      e.carry_in,
      e.available_budget,
      fl.id as lineup_id,
      fl.players,
      fl.captain_number,
      fl.coach_code
    from public.fantasy_gameweek_economy e
    left join public.fantasy_lineups fl
      on fl.fantasy_team_id = e.fantasy_team_id
     and fl.gameweek_id = e.gameweek_id
    where e.gameweek_id = v_gameweek.id
  loop
    v_matched_players := 0;
    v_distinct_players := 0;
    v_priced_players := 0;
    v_lineup_cost := 0;
    v_has_captain := false;
    v_has_coach := false;

    if v_row.lineup_id is not null then
      select
        count(sp.player_id),
        count(distinct sp.player_id),
        count(fgp.player_id),
        coalesce(sum(fgp.price), 0)
      into
        v_matched_players,
        v_distinct_players,
        v_priced_players,
        v_lineup_cost
      from unnest(v_row.players) as pick(raw_number)
      left join public.season_players sp
        on sp.season_id = v_gameweek.season_id
       and sp.active = true
       and pick.raw_number ~ '^[0-9]+$'
       and sp.jersey_number ~ '^[0-9]+$'
       and sp.jersey_number::integer = pick.raw_number::integer
      left join public.fantasy_gameweek_prices fgp
        on fgp.gameweek_id = v_gameweek.id
       and fgp.player_id = sp.player_id;

      v_has_captain :=
        v_row.captain_number is not null
        and exists (
          select 1
          from unnest(v_row.players) as captain_pick(raw_number)
          where captain_pick.raw_number ~ '^[0-9]+$'
            and captain_pick.raw_number::integer = v_row.captain_number::integer
        );

      v_has_coach :=
        v_row.coach_code is not null
        and exists (
          select 1
          from public.season_staff ss
          join public.staff_members sm on sm.id = ss.staff_id
          where ss.season_id = v_gameweek.season_id
            and ss.active = true
            and ss.fantasy_enabled = true
            and sm.code = v_row.coach_code
        );
    end if;

    v_valid :=
      v_row.lineup_id is not null
      and v_matched_players = 5
      and v_distinct_players = 5
      and v_priced_players = 5
      and v_has_captain
      and v_has_coach
      and v_lineup_cost <= v_row.available_budget;

    if v_valid then
      v_savings := greatest(v_row.available_budget - v_lineup_cost, 0);
      v_carry_out := least(v_savings, v_max_carry);
      v_finalized_count := v_finalized_count + 1;
    else
      v_lineup_cost := case
        when v_row.lineup_id is null then null
        else v_lineup_cost
      end;
      v_savings := 0;
      v_carry_out := 0;
      v_invalid_count := v_invalid_count + 1;
    end if;

    update public.fantasy_gameweek_economy
    set
      lineup_cost = v_lineup_cost,
      valid_lineup = v_valid,
      savings_generated = v_savings,
      carry_out = v_carry_out,
      finalized_at = now(),
      updated_at = now()
    where fantasy_team_id = v_row.fantasy_team_id
      and gameweek_id = v_gameweek.id;

    insert into public.fantasy_economy_ledger (
      fantasy_team_id,
      gameweek_id,
      entry_type,
      event_key,
      amount,
      metadata,
      created_by
    )
    values (
      v_row.fantasy_team_id,
      v_gameweek.id,
      'base_budget',
      'base_budget',
      v_row.base_budget,
      jsonb_build_object('source', 'gameweek_snapshot'),
      auth.uid()
    )
    on conflict (fantasy_team_id, gameweek_id, event_key)
    do update set
      amount = excluded.amount,
      metadata = excluded.metadata;

    insert into public.fantasy_economy_ledger (
      fantasy_team_id,
      gameweek_id,
      entry_type,
      event_key,
      amount,
      metadata,
      created_by
    )
    values (
      v_row.fantasy_team_id,
      v_gameweek.id,
      'carry_in',
      'carry_in',
      v_row.carry_in,
      jsonb_build_object('source', 'previous_gameweek'),
      auth.uid()
    )
    on conflict (fantasy_team_id, gameweek_id, event_key)
    do update set
      amount = excluded.amount,
      metadata = excluded.metadata;

    insert into public.fantasy_economy_ledger (
      fantasy_team_id,
      gameweek_id,
      entry_type,
      event_key,
      amount,
      metadata,
      created_by
    )
    values (
      v_row.fantasy_team_id,
      v_gameweek.id,
      'savings',
      'savings',
      v_carry_out,
      jsonb_build_object(
        'valid_lineup', v_valid,
        'available_budget', v_row.available_budget,
        'lineup_cost', v_lineup_cost,
        'raw_savings', v_savings,
        'carry_out', v_carry_out
      ),
      auth.uid()
    )
    on conflict (fantasy_team_id, gameweek_id, event_key)
    do update set
      amount = excluded.amount,
      metadata = excluded.metadata;

    if v_savings > v_carry_out then
      insert into public.fantasy_economy_ledger (
        fantasy_team_id,
        gameweek_id,
        entry_type,
        event_key,
        amount,
        metadata,
        created_by
      )
      values (
        v_row.fantasy_team_id,
        v_gameweek.id,
        'savings_cap',
        'savings_cap',
        -(v_savings - v_carry_out),
        jsonb_build_object(
          'max_carry', v_max_carry,
          'raw_savings', v_savings
        ),
        auth.uid()
      )
      on conflict (fantasy_team_id, gameweek_id, event_key)
      do update set
        amount = excluded.amount,
        metadata = excluded.metadata;
    else
      delete from public.fantasy_economy_ledger
      where fantasy_team_id = v_row.fantasy_team_id
        and gameweek_id = v_gameweek.id
        and event_key = 'savings_cap';
    end if;
  end loop;

  return jsonb_build_object(
    'gameweek_id', v_gameweek.id,
    'season_id', v_gameweek.season_id,
    'valid_lineups', v_finalized_count,
    'invalid_lineups', v_invalid_count,
    'max_carry', v_max_carry
  );
end;
$$;

create or replace function public.create_fantasy_economy_for_new_team()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_budget integer;
begin
  insert into public.fantasy_gameweek_economy (
    fantasy_team_id,
    gameweek_id,
    base_budget,
    carry_in
  )
  select
    new.id,
    gw.id,
    gw.base_budget,
    0
  from public.gameweeks gw
  where gw.season_id = new.season_id
    and gw.status = 'scheduled'
    and gw.deadline > now()
  on conflict (fantasy_team_id, gameweek_id) do nothing;

  insert into public.fantasy_economy_ledger (
    fantasy_team_id,
    gameweek_id,
    entry_type,
    event_key,
    amount,
    metadata,
    created_by
  )
  select
    e.fantasy_team_id,
    e.gameweek_id,
    'base_budget',
    'base_budget',
    e.base_budget,
    jsonb_build_object('source', 'joined_after_start'),
    new.user_id
  from public.fantasy_gameweek_economy e
  where e.fantasy_team_id = new.id
  on conflict (fantasy_team_id, gameweek_id, event_key) do nothing;

  select e.available_budget
    into v_current_budget
  from public.fantasy_gameweek_economy e
  join public.gameweeks gw on gw.id = e.gameweek_id
  where e.fantasy_team_id = new.id
    and gw.status = 'scheduled'
    and gw.deadline > now()
  order by gw.deadline asc, gw.id asc
  limit 1;

  if v_current_budget is not null then
    update public.fantasy_teams
    set cervezas = v_current_budget
    where id = new.id;
  end if;

  return new;
end;
$$;

revoke all on function public.create_fantasy_economy_for_new_team()
  from public, anon, authenticated;

drop trigger if exists trg_create_fantasy_economy_on_new_team
  on public.fantasy_teams;
create trigger trg_create_fantasy_economy_on_new_team
after insert on public.fantasy_teams
for each row execute function public.create_fantasy_economy_for_new_team();

create or replace function public.create_fantasy_economy_for_new_gameweek()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous_gameweek_id bigint;
  v_previous_deadline timestamptz;
  v_max_carry integer := 20;
begin
  if auth.uid() is null or not public.is_gazal_admin() then
    raise exception 'Admin permissions required';
  end if;

  if new.status = 'scheduled'
     and new.deadline > now()
     and exists (
       select 1
       from public.gameweeks gw
       where gw.id <> new.id
         and gw.season_id = new.season_id
         and gw.status = 'scheduled'
         and gw.deadline > now()
     ) then
    raise exception 'Another Fantasy gameweek is already open for season %', new.season_id;
  end if;

  select gw.id, gw.deadline
    into v_previous_gameweek_id, v_previous_deadline
  from public.gameweeks gw
  where gw.season_id = new.season_id
    and gw.id <> new.id
    and (
      gw.date < new.date
      or (gw.date = new.date and gw.id < new.id)
    )
  order by gw.date desc, gw.id desc
  limit 1;

  if v_previous_gameweek_id is not null
     and v_previous_deadline <= now() then
    perform public.finalize_fantasy_gameweek_economy(v_previous_gameweek_id);
  end if;

  select coalesce(fss.max_carry, 20)
    into v_max_carry
  from public.fantasy_season_settings fss
  where fss.season_id = new.season_id;

  v_max_carry := coalesce(v_max_carry, 20);

  insert into public.fantasy_gameweek_economy (
    fantasy_team_id,
    gameweek_id,
    base_budget,
    carry_in
  )
  select
    ft.id,
    new.id,
    new.base_budget,
    least(
      case
        when prev_e.finalized_at is not null and prev_e.valid_lineup
          then prev_e.carry_out
        else 0
      end,
      v_max_carry
    )
  from public.fantasy_teams ft
  left join public.fantasy_gameweek_economy prev_e
    on prev_e.fantasy_team_id = ft.id
   and prev_e.gameweek_id = v_previous_gameweek_id
  where ft.season_id = new.season_id
  on conflict (fantasy_team_id, gameweek_id) do nothing;

  insert into public.fantasy_economy_ledger (
    fantasy_team_id,
    gameweek_id,
    entry_type,
    event_key,
    amount,
    metadata,
    created_by
  )
  select
    e.fantasy_team_id,
    e.gameweek_id,
    'base_budget',
    'base_budget',
    e.base_budget,
    jsonb_build_object('source', 'gameweek_snapshot'),
    auth.uid()
  from public.fantasy_gameweek_economy e
  where e.gameweek_id = new.id
  on conflict (fantasy_team_id, gameweek_id, event_key) do nothing;

  insert into public.fantasy_economy_ledger (
    fantasy_team_id,
    gameweek_id,
    entry_type,
    event_key,
    amount,
    metadata,
    created_by
  )
  select
    e.fantasy_team_id,
    e.gameweek_id,
    'carry_in',
    'carry_in',
    e.carry_in,
    jsonb_build_object(
      'source', 'previous_gameweek',
      'previous_gameweek_id', v_previous_gameweek_id
    ),
    auth.uid()
  from public.fantasy_gameweek_economy e
  where e.gameweek_id = new.id
  on conflict (fantasy_team_id, gameweek_id, event_key) do nothing;

  update public.fantasy_teams ft
  set cervezas = e.available_budget
  from public.fantasy_gameweek_economy e
  where e.fantasy_team_id = ft.id
    and e.gameweek_id = new.id
    and ft.season_id = new.season_id;

  return new;
end;
$$;

revoke all on function public.create_fantasy_economy_for_new_gameweek()
  from public, anon, authenticated;

drop trigger if exists trg_create_fantasy_economy_on_new_gameweek
  on public.gameweeks;
create trigger trg_create_fantasy_economy_on_new_gameweek
after insert on public.gameweeks
for each row execute function public.create_fantasy_economy_for_new_gameweek();

grant execute on function public.finalize_fantasy_gameweek_economy(bigint)
  to authenticated;

comment on table public.fantasy_gameweek_economy is
  'Authoritative Fantasy budget state per team and gameweek. A skipped/invalid lineup finalizes with carry_out = 0.';
comment on column public.fantasy_gameweek_economy.carry_in is
  'Only carry from the immediately previous valid gameweek; users who skip rejoin with the new gameweek base budget.';
comment on column public.fantasy_gameweek_economy.carry_out is
  'Savings transferred to the next gameweek after applying the season max_carry limit.';
comment on column public.fantasy_teams.cervezas is
  'Compatibility cache for the currently opened Fantasy gameweek. The authoritative budget is fantasy_gameweek_economy.';
