-- Automatic Fantasy price evolution proposals.
--
-- Model:
--   performance = 40% current game + 35% last 3 games + 25% season
--   target price = 10 + 0.8 * performance + mild global-economy inflation
--   previous price keeps 65% inertia for established players
--   new players (first 3 appearances) keep 80% inertia
--   max move: +/-2 per game, or +/-1 for new players
--   market-health guard: the five cheapest proposals must stay <= 80% of the
--   season base budget, so a returning user can still build a sensible five.

create table if not exists public.fantasy_price_proposals (
  id bigint generated by default as identity primary key,
  season_id text not null,
  source_match_id text not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  previous_price integer not null check (previous_price > 0),
  game_pir numeric(8,2),
  recent_pir numeric(8,2),
  season_pir numeric(8,2),
  games_played integer not null default 0 check (games_played >= 0),
  blended_pir numeric(8,2),
  performance_target numeric(8,2),
  inflation_adjustment numeric(6,2) not null default 0,
  max_change integer not null check (max_change between 0 and 5),
  proposed_price integer not null check (proposed_price > 0),
  reviewed_price integer check (reviewed_price is null or reviewed_price > 0),
  status text not null default 'pending'
    check (status in ('pending','reviewed','applied')),
  generated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (season_id, source_match_id, player_id)
);

create index if not exists fantasy_price_proposals_season_generated_idx
  on public.fantasy_price_proposals(season_id, generated_at desc);
create index if not exists fantasy_price_proposals_match_idx
  on public.fantasy_price_proposals(source_match_id);

alter table public.fantasy_price_proposals enable row level security;
revoke all on public.fantasy_price_proposals from anon;
grant select, update on public.fantasy_price_proposals to authenticated;

drop policy if exists "fantasy_price_proposals_admin_read"
  on public.fantasy_price_proposals;
create policy "fantasy_price_proposals_admin_read"
  on public.fantasy_price_proposals
  for select to authenticated
  using ((select public.is_gazal_admin()));

drop policy if exists "fantasy_price_proposals_admin_update"
  on public.fantasy_price_proposals;
create policy "fantasy_price_proposals_admin_update"
  on public.fantasy_price_proposals
  for update to authenticated
  using ((select public.is_gazal_admin()))
  with check ((select public.is_gazal_admin()));

create or replace function public.generate_fantasy_price_proposals(
  p_season_id text,
  p_match_id text default null
)
returns table (
  player_id bigint,
  previous_price integer,
  game_pir numeric,
  recent_pir numeric,
  season_pir numeric,
  games_played integer,
  blended_pir numeric,
  inflation_adjustment numeric,
  proposed_price integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_match public.matches%rowtype;
  v_latest_gameweek_id bigint;
  v_avg_carry numeric := 0;
  v_base_budget integer := 80;
  v_inflation numeric := 0;
  v_affordability_limit integer;
  v_cheapest_five integer;
  v_changed integer;
begin
  if v_uid is null or not public.is_gazal_admin() then
    raise exception 'Admin permissions required';
  end if;

  if p_match_id is null then
    select * into v_match
    from public.matches
    where season = p_season_id
      and status = 'published'
    order by date desc, id desc
    limit 1;
  else
    select * into v_match
    from public.matches
    where id = p_match_id
      and season = p_season_id
      and status = 'published';
  end if;

  if not found then
    raise exception 'No published match found for season %', p_season_id;
  end if;

  select coalesce(fss.base_budget, 80)
    into v_base_budget
  from public.fantasy_season_settings fss
  where fss.season_id = p_season_id;

  v_base_budget := coalesce(v_base_budget, 80);
  v_affordability_limit := floor(v_base_budget * 0.80)::integer;

  select gw.id
    into v_latest_gameweek_id
  from public.gameweeks gw
  where gw.season_id = p_season_id
    and exists (
      select 1
      from public.fantasy_gameweek_economy e
      where e.gameweek_id = gw.id
        and e.finalized_at is not null
    )
  order by gw.date desc, gw.id desc
  limit 1;

  if v_latest_gameweek_id is not null then
    select coalesce(avg(e.carry_out), 0)
      into v_avg_carry
    from public.fantasy_gameweek_economy e
    where e.gameweek_id = v_latest_gameweek_id
      and e.finalized_at is not null;
  end if;

  -- At most +1 point of systemic inflation at full ordinary carry. This is
  -- intentionally much smaller than the maximum 20-30 beer carry advantage.
  v_inflation := least(
    1.0,
    greatest(0.0, (v_avg_carry / greatest(v_base_budget, 1)) * 4.0)
  );

  delete from public.fantasy_price_proposals
  where season_id = p_season_id
    and source_match_id = v_match.id
    and status = 'pending';

  insert into public.fantasy_price_proposals (
    season_id,
    source_match_id,
    player_id,
    previous_price,
    game_pir,
    recent_pir,
    season_pir,
    games_played,
    blended_pir,
    performance_target,
    inflation_adjustment,
    max_change,
    proposed_price
  )
  select
    p_season_id,
    v_match.id,
    fm.player_id,
    fm.price,
    s.game_pir,
    s.recent_pir,
    s.season_pir,
    s.games_played,
    case
      when s.game_pir is null then null
      else round(
        (0.40*s.game_pir + 0.35*s.recent_pir + 0.25*s.season_pir)::numeric,
        2
      )
    end,
    case
      when s.game_pir is null then null
      else round(
        least(
          30.0,
          greatest(
            8.0,
            10.0
              + 0.8*(0.40*s.game_pir + 0.35*s.recent_pir + 0.25*s.season_pir)
              + v_inflation
          )
        )::numeric,
        2
      )
    end,
    v_inflation,
    case when s.games_played between 1 and 3 then 1 else 2 end,
    case
      -- A DNP does not penalize or inflate a player.
      when s.game_pir is null then fm.price
      else greatest(
        8,
        least(
          30,
          fm.price + (case when s.games_played between 1 and 3 then 1 else 2 end),
          greatest(
            fm.price - (case when s.games_played between 1 and 3 then 1 else 2 end),
            round(
              fm.price
                * (case when s.games_played between 1 and 3 then 0.80 else 0.65 end)
              + least(
                  30.0,
                  greatest(
                    8.0,
                    10.0
                      + 0.8*(0.40*s.game_pir + 0.35*s.recent_pir + 0.25*s.season_pir)
                      + v_inflation
                  )
                )
                * (case when s.games_played between 1 and 3 then 0.20 else 0.35 end)
            )::integer
          )
        )
      )
    end
  from public.fantasy_player_market fm
  join public.season_players sp
    on sp.season_id = fm.season_id
   and sp.player_id = fm.player_id
   and sp.active = true
  left join lateral (
    select
      (
        select pms0.pir::numeric
        from public.player_match_stats pms0
        where pms0.match_id = v_match.id
          and pms0.player_id = fm.player_id
        limit 1
      ) as game_pir,
      (
        select avg(z.pir)::numeric
        from (
          select pms1.pir
          from public.player_match_stats pms1
          join public.matches m1 on m1.id = pms1.match_id
          where pms1.player_id = fm.player_id
            and m1.season = p_season_id
            and m1.status = 'published'
            and (
              m1.date < v_match.date
              or (m1.date = v_match.date and m1.id <= v_match.id)
            )
          order by m1.date desc, m1.id desc
          limit 3
        ) z
      ) as recent_pir,
      (
        select avg(pms2.pir)::numeric
        from public.player_match_stats pms2
        join public.matches m2 on m2.id = pms2.match_id
        where pms2.player_id = fm.player_id
          and m2.season = p_season_id
          and m2.status = 'published'
          and (
            m2.date < v_match.date
            or (m2.date = v_match.date and m2.id <= v_match.id)
          )
      ) as season_pir,
      (
        select count(*)::integer
        from public.player_match_stats pms3
        join public.matches m3 on m3.id = pms3.match_id
        where pms3.player_id = fm.player_id
          and m3.season = p_season_id
          and m3.status = 'published'
          and (
            m3.date < v_match.date
            or (m3.date = v_match.date and m3.id <= v_match.id)
          )
      ) as games_played
  ) s on true
  where fm.season_id = p_season_id
    and fm.enabled = true;

  -- Market-health guard. Reductions never exceed each player's normal change
  -- bound; if the existing market is already too expensive to satisfy the
  -- affordability rule, generation fails rather than silently breaking it.
  loop
    select coalesce(sum(x.proposed_price), 0)
      into v_cheapest_five
    from (
      select fpp.proposed_price
      from public.fantasy_price_proposals fpp
      where fpp.season_id = p_season_id
        and fpp.source_match_id = v_match.id
      order by fpp.proposed_price asc, fpp.player_id asc
      limit 5
    ) x;

    exit when v_cheapest_five <= v_affordability_limit;

    with cheapest as (
      select fpp.id
      from public.fantasy_price_proposals fpp
      where fpp.season_id = p_season_id
        and fpp.source_match_id = v_match.id
        and fpp.proposed_price > greatest(8, fpp.previous_price - fpp.max_change)
      order by fpp.proposed_price asc, fpp.player_id asc
      limit 5
    )
    update public.fantasy_price_proposals fpp
    set proposed_price = fpp.proposed_price - 1
    where fpp.id in (select id from cheapest);

    get diagnostics v_changed = row_count;
    if v_changed = 0 then
      raise exception 'Cannot preserve affordable five-player market within configured change limits';
    end if;
  end loop;

  return query
  select
    fpp.player_id,
    fpp.previous_price,
    fpp.game_pir,
    fpp.recent_pir,
    fpp.season_pir,
    fpp.games_played,
    fpp.blended_pir,
    fpp.inflation_adjustment,
    fpp.proposed_price
  from public.fantasy_price_proposals fpp
  where fpp.season_id = p_season_id
    and fpp.source_match_id = v_match.id
  order by fpp.proposed_price desc, fpp.player_id;
end;
$$;

revoke all on function public.generate_fantasy_price_proposals(text, text)
  from public, anon;
grant execute on function public.generate_fantasy_price_proposals(text, text)
  to authenticated;

comment on table public.fantasy_price_proposals is
  'Admin-reviewed Fantasy price suggestions generated from published game, recent and season PIR plus bounded economy inflation.';
