-- Gazalbide Stats: baseline of the pre-existing Fantasy schema.
-- Captured from production before introducing repository-managed migrations.
-- Intentionally idempotent so it can be recorded safely on the existing project
-- and can also recreate the original Fantasy schema in a fresh Supabase branch.

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'player_status_enum'
  ) then
    create type public.player_status_enum as enum ('available', 'doubtful', 'injured');
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.gameweeks (
  id bigint generated by default as identity primary key,
  name text,
  opponent text,
  date date not null,
  deadline timestamptz not null,
  match_id text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'played', 'scored')),
  created_at timestamptz not null default now(),
  stats_file text
);

create table if not exists public.fantasy_teams (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  name text not null,
  cervezas integer not null default 80,
  created_at timestamptz not null default now()
);

create table if not exists public.fantasy_lineups (
  id uuid primary key default gen_random_uuid(),
  fantasy_team_id uuid not null references public.fantasy_teams(id) on delete cascade,
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  players text[] not null check (array_length(players, 1) = 5),
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  captain_number smallint,
  coach_code text,
  unique (fantasy_team_id, gameweek_id)
);

create table if not exists public.player_statuses (
  id uuid primary key default gen_random_uuid(),
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  player_number smallint not null,
  status public.player_status_enum not null default 'available',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  unique (gameweek_id, player_number)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$;

create or replace function public.create_empty_lineups_for_new_team()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.fantasy_lineups (
    fantasy_team_id,
    gameweek_id,
    players,
    captain_number,
    coach_code
  )
  select
    new.id,
    gw.id,
    array['-1','-1','-1','-1','-1']::text[],
    null,
    'david'
  from public.gameweeks gw
  on conflict (fantasy_team_id, gameweek_id) do nothing;
  return new;
end;
$$;

create or replace function public.create_empty_lineups_for_new_gameweek()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.fantasy_lineups (
    fantasy_team_id,
    gameweek_id,
    players,
    captain_number,
    coach_code
  )
  select
    ft.id,
    new.id,
    array['-1','-1','-1','-1','-1']::text[],
    null,
    'david'
  from public.fantasy_teams ft
  on conflict (fantasy_team_id, gameweek_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists trg_create_empty_lineups_on_new_team on public.fantasy_teams;
create trigger trg_create_empty_lineups_on_new_team
after insert on public.fantasy_teams
for each row execute function public.create_empty_lineups_for_new_team();

drop trigger if exists trg_create_empty_lineups_on_new_gameweek on public.gameweeks;
create trigger trg_create_empty_lineups_on_new_gameweek
after insert on public.gameweeks
for each row execute function public.create_empty_lineups_for_new_gameweek();

alter table public.profiles enable row level security;
alter table public.gameweeks enable row level security;
alter table public.fantasy_teams enable row level security;
alter table public.fantasy_lineups enable row level security;
alter table public.player_statuses enable row level security;

-- profiles
drop policy if exists "Public read profiles" on public.profiles;
create policy "Public read profiles" on public.profiles
  for select to anon, authenticated using (true);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

-- gameweeks
drop policy if exists "Authenticated can view gameweeks" on public.gameweeks;
create policy "Authenticated can view gameweeks" on public.gameweeks
  for select using (auth.role() = 'authenticated');

drop policy if exists "Admins can insert gameweeks" on public.gameweeks;
create policy "Admins can insert gameweeks" on public.gameweeks
  for insert with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
  );

drop policy if exists "Admins can update gameweeks" on public.gameweeks;
create policy "Admins can update gameweeks" on public.gameweeks
  for update using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
  );

drop policy if exists "Admins can delete gameweeks" on public.gameweeks;
create policy "Admins can delete gameweeks" on public.gameweeks
  for delete using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
  );

-- fantasy teams
drop policy if exists "Public read fantasy_teams for ranking" on public.fantasy_teams;
create policy "Public read fantasy_teams for ranking" on public.fantasy_teams
  for select using (true);

drop policy if exists "Users can insert own teams" on public.fantasy_teams;
create policy "Users can insert own teams" on public.fantasy_teams
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own teams" on public.fantasy_teams;
create policy "Users can update own teams" on public.fantasy_teams
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own teams" on public.fantasy_teams;
create policy "Users can delete own teams" on public.fantasy_teams
  for delete using (auth.uid() = user_id);

-- fantasy lineups
drop policy if exists "Public read fantasy lineups" on public.fantasy_lineups;
create policy "Public read fantasy lineups" on public.fantasy_lineups
  for select to anon, authenticated using (true);

drop policy if exists "Public read fantasy_lineups for ranking" on public.fantasy_lineups;
create policy "Public read fantasy_lineups for ranking" on public.fantasy_lineups
  for select using (true);

drop policy if exists "Users can view own lineups" on public.fantasy_lineups;
create policy "Users can view own lineups" on public.fantasy_lineups
  for select using (
    fantasy_team_id in (select ft.id from public.fantasy_teams ft where ft.user_id = auth.uid())
  );

drop policy if exists "Users can insert own lineups before deadline" on public.fantasy_lineups;
create policy "Users can insert own lineups before deadline" on public.fantasy_lineups
  for insert with check (
    fantasy_team_id in (select ft.id from public.fantasy_teams ft where ft.user_id = auth.uid())
    and exists (
      select 1 from public.gameweeks gw
      where gw.id = fantasy_lineups.gameweek_id
        and gw.status = 'scheduled'
        and now() < gw.deadline
    )
  );

drop policy if exists "Users can update own lineups before deadline" on public.fantasy_lineups;
create policy "Users can update own lineups before deadline" on public.fantasy_lineups
  for update using (
    fantasy_team_id in (select ft.id from public.fantasy_teams ft where ft.user_id = auth.uid())
    and exists (
      select 1 from public.gameweeks gw
      where gw.id = fantasy_lineups.gameweek_id
        and gw.status = 'scheduled'
        and now() < gw.deadline
    )
  );

drop policy if exists "Users can delete own lineups before deadline" on public.fantasy_lineups;
create policy "Users can delete own lineups before deadline" on public.fantasy_lineups
  for delete using (
    fantasy_team_id in (select ft.id from public.fantasy_teams ft where ft.user_id = auth.uid())
    and exists (
      select 1 from public.gameweeks gw
      where gw.id = fantasy_lineups.gameweek_id
        and gw.status = 'scheduled'
        and now() < gw.deadline
    )
  );

-- player statuses
drop policy if exists "Anyone can read player statuses" on public.player_statuses;
create policy "Anyone can read player statuses" on public.player_statuses
  for select using (true);

drop policy if exists "Admins can manage player statuses" on public.player_statuses;
create policy "Admins can manage player statuses" on public.player_statuses
  for all to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
  );
