-- Gazalbide Stats: Web Push notifications for the PWA.
-- Private VAPID/dispatcher secrets are provisioned separately in Supabase Vault.

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create table if not exists public.notification_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  enabled boolean not null default true,
  new_gameweek boolean not null default true,
  deadline_24h boolean not null default true,
  deadline_1h boolean not null default true,
  player_status boolean not null default true,
  match_live boolean not null default true,
  result_published boolean not null default true,
  prices_updated boolean not null default true,
  economy_ready boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  expiration_time bigint,
  user_agent text,
  active boolean not null default true,
  failure_count integer not null default 0 check (failure_count >= 0),
  last_success_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_active_idx
  on public.push_subscriptions(user_id, active);

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  notification_type text not null check (notification_type in (
    'new_gameweek','deadline_24h','deadline_1h','player_status',
    'match_live','result_published','prices_updated','economy_ready'
  )),
  event_key text not null,
  title text not null,
  body text not null,
  route text not null default '/',
  tag text,
  payload jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending','sending','sent','skipped','failed')),
  attempts integer not null default 0 check (attempts >= 0),
  claimed_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, event_key)
);
create index if not exists notification_outbox_due_idx
  on public.notification_outbox(status, scheduled_for);
create index if not exists notification_outbox_user_created_idx
  on public.notification_outbox(user_id, created_at desc);

create table if not exists public.notification_server_config (
  singleton boolean primary key default true check (singleton),
  vapid_public_key text not null,
  vapid_subject text not null,
  dispatch_secret_hash text not null,
  edge_function_url text not null,
  updated_at timestamptz not null default now()
);

insert into public.notification_server_config (
  singleton, vapid_public_key, vapid_subject, dispatch_secret_hash, edge_function_url
) values (
  true,
  'BELh6Y23K6Q2_ZqMlkGo60oMzn61JSgMUbTR0sgqSORhjuZFMKlZjn0VtfTPLL2-BUY0acdQSxLXSRXc-x5Ja4Y',
  'https://davidperez3.github.io/gazalbide-stats/',
  '62fa194c9587ce1fe95f874e7382326fae86ffe03f462a5f408445fd55abf56a',
  'https://xsqjkasrcxbyrdyxevyu.supabase.co/functions/v1/push-dispatch'
)
on conflict (singleton) do update set
  vapid_public_key = excluded.vapid_public_key,
  vapid_subject = excluded.vapid_subject,
  dispatch_secret_hash = excluded.dispatch_secret_hash,
  edge_function_url = excluded.edge_function_url,
  updated_at = now();

alter table public.notification_preferences enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_outbox enable row level security;
alter table public.notification_server_config enable row level security;

revoke all on public.notification_server_config from public, anon, authenticated;
revoke insert, update, delete on public.notification_outbox from anon, authenticated;
revoke all on public.push_subscriptions from anon;
revoke all on public.notification_preferences from anon;
grant select, insert, update on public.notification_preferences to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant select on public.notification_outbox to authenticated;

drop policy if exists notification_preferences_own on public.notification_preferences;
create policy notification_preferences_own on public.notification_preferences
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists push_subscriptions_own on public.push_subscriptions;
create policy push_subscriptions_own on public.push_subscriptions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists notification_outbox_own_read on public.notification_outbox;
create policy notification_outbox_own_read on public.notification_outbox
  for select to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.notification_create_preferences()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notification_preferences(user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;
revoke all on function public.notification_create_preferences() from public, anon, authenticated;

drop trigger if exists trg_notification_preferences_profile on public.profiles;
create trigger trg_notification_preferences_profile
after insert on public.profiles
for each row execute function public.notification_create_preferences();

insert into public.notification_preferences(user_id)
select id from public.profiles
on conflict (user_id) do nothing;

create or replace function public.get_push_public_config()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'vapidPublicKey', vapid_public_key,
    'supportedTypes', jsonb_build_array(
      'new_gameweek','deadline_24h','deadline_1h','player_status',
      'match_live','result_published','prices_updated','economy_ready'
    )
  )
  from public.notification_server_config
  where singleton = true;
$$;
revoke all on function public.get_push_public_config() from public;
grant execute on function public.get_push_public_config() to authenticated;

create or replace function public.register_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth_secret text,
  p_expiration_time bigint default null,
  p_user_agent text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_id uuid;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if coalesce(length(p_endpoint),0) < 10 or coalesce(length(p_p256dh),0) < 10 or coalesce(length(p_auth_secret),0) < 5 then
    raise exception 'Invalid push subscription';
  end if;

  insert into public.push_subscriptions(
    user_id, endpoint, p256dh, auth_secret, expiration_time, user_agent, active, failure_count, updated_at
  ) values (
    v_uid, p_endpoint, p_p256dh, p_auth_secret, p_expiration_time, left(p_user_agent,500), true, 0, now()
  )
  on conflict (endpoint) do update set
    user_id = excluded.user_id,
    p256dh = excluded.p256dh,
    auth_secret = excluded.auth_secret,
    expiration_time = excluded.expiration_time,
    user_agent = excluded.user_agent,
    active = true,
    failure_count = 0,
    updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;
revoke all on function public.register_push_subscription(text,text,text,bigint,text) from public, anon;
grant execute on function public.register_push_subscription(text,text,text,bigint,text) to authenticated;

create or replace function public.unregister_push_subscription(p_endpoint text)
returns void
language sql
security invoker
set search_path = public
as $$
  delete from public.push_subscriptions
  where user_id = (select auth.uid()) and endpoint = p_endpoint;
$$;
revoke all on function public.unregister_push_subscription(text) from public, anon;
grant execute on function public.unregister_push_subscription(text) to authenticated;

create or replace function public.notification_enqueue_user(
  p_user_id uuid,
  p_type text,
  p_event_key text,
  p_title text,
  p_body text,
  p_route text default '/',
  p_tag text default null,
  p_payload jsonb default '{}'::jsonb,
  p_scheduled_for timestamptz default now()
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notification_outbox(
    user_id, notification_type, event_key, title, body, route, tag, payload, scheduled_for
  ) values (
    p_user_id, p_type, p_event_key, p_title, p_body,
    coalesce(nullif(p_route,''),'/'), p_tag, coalesce(p_payload,'{}'::jsonb), coalesce(p_scheduled_for,now())
  )
  on conflict (user_id,event_key) do nothing;
end;
$$;
revoke all on function public.notification_enqueue_user(uuid,text,text,text,text,text,text,jsonb,timestamptz)
  from public, anon, authenticated;

create or replace function public.notification_schedule_gameweek_for_user(p_user_id uuid, p_gameweek_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  gw public.gameweeks%rowtype;
  v_name text;
begin
  select * into gw from public.gameweeks where id = p_gameweek_id;
  if not found or gw.status <> 'scheduled' or gw.deadline <= now() then return; end if;
  v_name := coalesce(gw.name, 'Nueva jornada');

  perform public.notification_enqueue_user(
    p_user_id,'deadline_24h','gw:'||gw.id||':deadline24',
    'Fantasy · quedan 24 horas',
    v_name || case when gw.opponent is not null then ' · vs '||gw.opponent else '' end || '. Revisa tu alineación.',
    '/fantasy','fantasy-deadline-'||gw.id,
    jsonb_build_object('gameweekId',gw.id),
    greatest(now(), gw.deadline - interval '24 hours')
  );
  perform public.notification_enqueue_user(
    p_user_id,'deadline_1h','gw:'||gw.id||':deadline1',
    'Fantasy · queda 1 hora',
    'Tu alineación todavía necesita atención antes del cierre.',
    '/fantasy','fantasy-deadline-'||gw.id,
    jsonb_build_object('gameweekId',gw.id,'requiresInvalidLineup',true),
    greatest(now(), gw.deadline - interval '1 hour')
  );
end;
$$;
revoke all on function public.notification_schedule_gameweek_for_user(uuid,bigint)
  from public, anon, authenticated;

create or replace function public.notification_gameweek_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  if new.status <> 'scheduled' then return new; end if;
  for r in select user_id from public.fantasy_teams where season_id = new.season_id loop
    perform public.notification_enqueue_user(
      r.user_id,'new_gameweek','gw:'||new.id||':open',
      'Nueva jornada Fantasy',
      coalesce(new.name,'Jornada') || case when new.opponent is not null then ' · vs '||new.opponent else '' end || ' ya está abierta.',
      '/fantasy','fantasy-gameweek-'||new.id,jsonb_build_object('gameweekId',new.id),now()
    );
    perform public.notification_schedule_gameweek_for_user(r.user_id,new.id);
  end loop;
  return new;
end;
$$;
revoke all on function public.notification_gameweek_created() from public, anon, authenticated;
drop trigger if exists trg_notification_gameweek_created on public.gameweeks;
create trigger trg_notification_gameweek_created
after insert on public.gameweeks
for each row execute function public.notification_gameweek_created();

create or replace function public.notification_team_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  for r in select id from public.gameweeks where season_id=new.season_id and status='scheduled' and deadline>now() loop
    perform public.notification_schedule_gameweek_for_user(new.user_id,r.id);
  end loop;
  return new;
end;
$$;
revoke all on function public.notification_team_created() from public, anon, authenticated;
drop trigger if exists trg_notification_team_created on public.fantasy_teams;
create trigger trg_notification_team_created
after insert on public.fantasy_teams
for each row execute function public.notification_team_created();

create or replace function public.notification_lineup_valid(p_user_id uuid, p_gameweek_id bigint)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_lineup public.fantasy_lineups%rowtype;
  v_team public.fantasy_teams%rowtype;
  v_gw public.gameweeks%rowtype;
  v_count integer := 0;
  v_distinct integer := 0;
  v_priced integer := 0;
  v_cost integer := 0;
  v_budget integer := 0;
begin
  select * into v_gw from public.gameweeks where id=p_gameweek_id;
  if not found then return false; end if;
  select * into v_team from public.fantasy_teams where user_id=p_user_id and season_id=v_gw.season_id limit 1;
  if not found then return false; end if;
  select * into v_lineup from public.fantasy_lineups where fantasy_team_id=v_team.id and gameweek_id=p_gameweek_id limit 1;
  if not found or array_length(v_lineup.players,1)<>5 or v_lineup.captain_number is null or v_lineup.coach_code is null then return false; end if;

  select count(sp.player_id), count(distinct sp.player_id), count(coalesce(fgp.player_id,fpm.player_id)),
         coalesce(sum(coalesce(fgp.price,fpm.price)),0)
    into v_count,v_distinct,v_priced,v_cost
  from unnest(v_lineup.players) p(raw_number)
  left join public.season_players sp
    on sp.season_id=v_gw.season_id and sp.active=true
   and p.raw_number ~ '^[0-9]+$' and sp.jersey_number ~ '^[0-9]+$'
   and sp.jersey_number::integer=p.raw_number::integer
  left join public.fantasy_gameweek_prices fgp
    on fgp.gameweek_id=v_gw.id and fgp.player_id=sp.player_id
  left join public.fantasy_player_market fpm
    on fpm.season_id=v_gw.season_id and fpm.player_id=sp.player_id and fpm.enabled=true;

  select coalesce(e.available_budget,v_gw.base_budget)
    into v_budget
  from (select 1) x
  left join public.fantasy_gameweek_economy e
    on e.fantasy_team_id=v_team.id and e.gameweek_id=v_gw.id;

  return v_count=5 and v_distinct=5 and v_priced=5
    and v_cost<=coalesce(v_budget,v_gw.base_budget)
    and exists (
      select 1 from unnest(v_lineup.players) c(raw_number)
      where c.raw_number ~ '^[0-9]+$' and c.raw_number::integer=v_lineup.captain_number::integer
    );
end;
$$;
revoke all on function public.notification_lineup_valid(uuid,bigint) from public, anon, authenticated;

create or replace function public.notification_player_status_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r record; v_label text;
begin
  if new.status::text='available' then return new; end if;
  if tg_op='UPDATE' and old.status::text=new.status::text and coalesce(old.note,'')=coalesce(new.note,'') then return new; end if;
  v_label := case new.status::text when 'doubtful' then 'dudoso' when 'injured' then 'no disponible' else new.status::text end;
  for r in
    select distinct ft.user_id
    from public.fantasy_lineups fl
    join public.fantasy_teams ft on ft.id=fl.fantasy_team_id
    join public.gameweeks gw on gw.id=fl.gameweek_id
    where fl.gameweek_id=new.gameweek_id and gw.status='scheduled' and gw.deadline>now()
      and new.player_number::text=any(fl.players)
  loop
    perform public.notification_enqueue_user(
      r.user_id,'player_status',
      'status:'||new.gameweek_id||':'||new.player_number||':'||new.status::text,
      'Revisa tu alineación Fantasy',
      '#' || new.player_number || ' figura como ' || v_label || case when nullif(new.note,'') is not null then ': '||new.note else '.' end,
      '/fantasy','fantasy-status-'||new.gameweek_id||'-'||new.player_number,
      jsonb_build_object('gameweekId',new.gameweek_id,'playerNumber',new.player_number),now()
    );
  end loop;
  return new;
end;
$$;
revoke all on function public.notification_player_status_changed() from public, anon, authenticated;
drop trigger if exists trg_notification_player_status on public.player_statuses;
create trigger trg_notification_player_status
after insert or update of status,note on public.player_statuses
for each row execute function public.notification_player_status_changed();

create or replace function public.notification_match_status_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  if new.status='live' and (tg_op='INSERT' or old.status is distinct from new.status) then
    for r in select id from public.profiles loop
      perform public.notification_enqueue_user(
        r.id,'match_live','match:'||new.id||':live',
        '🔴 Gazalbide está en directo',
        'Ya puedes seguir el partido' || case when exists(select 1 from public.fantasy_teams ft where ft.user_id=r.id and ft.season_id=new.season) then ' y tu Fantasy Live.' else '.' end,
        '/live/'||new.id,'live-match-'||new.id,jsonb_build_object('matchId',new.id),now()
      );
    end loop;
  elsif new.status='published' and tg_op='UPDATE' and old.status is distinct from new.status then
    for r in select id from public.profiles loop
      perform public.notification_enqueue_user(
        r.id,'result_published','match:'||new.id||':published:v'||new.publication_version,
        'Resultado oficial publicado',
        'Gazalbide '||new.gazal_pts||'–'||new.opp_pts||' '||new.opponent||'. Ya están disponibles las estadísticas oficiales.',
        '/partido/'||new.id,'match-result-'||new.id,jsonb_build_object('matchId',new.id),now()
      );
    end loop;
  end if;
  return new;
end;
$$;
revoke all on function public.notification_match_status_changed() from public, anon, authenticated;
drop trigger if exists trg_notification_match_status on public.matches;
create trigger trg_notification_match_status
after insert or update of status,publication_version on public.matches
for each row execute function public.notification_match_status_changed();

create or replace function public.notification_prices_applied()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  if new.status='applied' and (tg_op='INSERT' or old.status is distinct from new.status) then
    for r in select user_id from public.fantasy_teams where season_id=new.season_id loop
      perform public.notification_enqueue_user(
        r.user_id,'prices_updated','prices:'||new.source_match_id||':applied',
        'Nuevos precios Fantasy',
        'Los precios tras el último partido ya están actualizados.',
        '/fantasy','fantasy-prices-'||new.source_match_id,jsonb_build_object('matchId',new.source_match_id),now()
      );
    end loop;
  end if;
  return new;
end;
$$;
revoke all on function public.notification_prices_applied() from public, anon, authenticated;
drop trigger if exists trg_notification_prices_applied on public.fantasy_price_proposals;
create trigger trg_notification_prices_applied
after insert or update of status on public.fantasy_price_proposals
for each row execute function public.notification_prices_applied();

create or replace function public.notification_economy_ready()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_uid uuid;
begin
  if new.finalized_at is null or not new.valid_lineup or new.carry_out<=0 then return new; end if;
  if tg_op='UPDATE' and old.finalized_at is not null then return new; end if;
  select user_id into v_uid from public.fantasy_teams where id=new.fantasy_team_id;
  if v_uid is not null then
    perform public.notification_enqueue_user(
      v_uid,'economy_ready','economy:'||new.gameweek_id||':ready',
      'Te sobran '||new.carry_out||' 🍺',
      'Ya puedes conservarlas para la próxima jornada o jugarlas en Le Gazal.',
      '/fantasy/le-gazal','fantasy-economy-'||new.gameweek_id,
      jsonb_build_object('gameweekId',new.gameweek_id,'beers',new.carry_out),now()
    );
  end if;
  return new;
end;
$$;
revoke all on function public.notification_economy_ready() from public, anon, authenticated;
drop trigger if exists trg_notification_economy_ready on public.fantasy_gameweek_economy;
create trigger trg_notification_economy_ready
after insert or update of finalized_at,valid_lineup,carry_out on public.fantasy_gameweek_economy
for each row execute function public.notification_economy_ready();

create or replace function public.notification_type_enabled(p_user_id uuid,p_type text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(p.enabled,false) and case p_type
    when 'new_gameweek' then p.new_gameweek
    when 'deadline_24h' then p.deadline_24h
    when 'deadline_1h' then p.deadline_1h
    when 'player_status' then p.player_status
    when 'match_live' then p.match_live
    when 'result_published' then p.result_published
    when 'prices_updated' then p.prices_updated
    when 'economy_ready' then p.economy_ready
    else false end
  from public.notification_preferences p where p.user_id=p_user_id;
$$;
revoke all on function public.notification_type_enabled(uuid,text) from public, anon, authenticated;

create or replace function public.notification_delivery_eligible(o public.notification_outbox)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare v_gw bigint; v_match text;
begin
  if not coalesce(public.notification_type_enabled(o.user_id,o.notification_type),false) then return false; end if;

  if o.notification_type in ('deadline_24h','deadline_1h') then
    v_gw := nullif(o.payload->>'gameweekId','')::bigint;
    if not exists(select 1 from public.gameweeks gw where gw.id=v_gw and gw.status='scheduled' and gw.deadline>now()) then return false; end if;
    if o.notification_type='deadline_1h' and public.notification_lineup_valid(o.user_id,v_gw) then return false; end if;
  elsif o.notification_type='new_gameweek' then
    v_gw := nullif(o.payload->>'gameweekId','')::bigint;
    if not exists(select 1 from public.gameweeks gw where gw.id=v_gw and gw.status='scheduled' and gw.deadline>now()) then return false; end if;
  elsif o.notification_type='match_live' then
    v_match := o.payload->>'matchId';
    if not exists(select 1 from public.matches m where m.id=v_match and m.status='live') then return false; end if;
  end if;
  return true;
exception when others then
  return false;
end;
$$;
revoke all on function public.notification_delivery_eligible(public.notification_outbox)
  from public, anon, authenticated;

create or replace function public.claim_push_notification_batch(p_limit integer default 100)
returns setof public.notification_outbox
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.notification_outbox
  set status='pending', claimed_at=null, updated_at=now()
  where status='sending' and claimed_at < now()-interval '10 minutes' and attempts<4;

  update public.notification_outbox o
  set status='skipped', last_error='preference_or_condition', updated_at=now()
  where o.status='pending' and o.scheduled_for<=now()
    and not public.notification_delivery_eligible(o);

  return query
  with picked as (
    select id from public.notification_outbox o
    where o.status='pending' and o.scheduled_for<=now()
      and public.notification_delivery_eligible(o)
    order by o.scheduled_for,o.id
    for update skip locked
    limit greatest(1,least(coalesce(p_limit,100),250))
  )
  update public.notification_outbox o
  set status='sending', attempts=o.attempts+1, claimed_at=now(), updated_at=now()
  from picked
  where o.id=picked.id
  returning o.*;
end;
$$;
revoke all on function public.claim_push_notification_batch(integer) from public, anon, authenticated;
grant execute on function public.claim_push_notification_batch(integer) to service_role;

create or replace function public.notification_push_server_secrets(p_dispatch_key text)
returns jsonb
language plpgsql
security definer
set search_path = public, vault
as $$
declare cfg public.notification_server_config%rowtype; v_private text;
begin
  select * into cfg from public.notification_server_config where singleton=true;
  if not found or encode(digest(coalesce(p_dispatch_key,''),'sha256'),'hex')<>cfg.dispatch_secret_hash then
    raise exception 'Invalid dispatcher key';
  end if;
  select decrypted_secret into v_private from vault.decrypted_secrets where name='gazalbide_vapid_private' order by created_at desc limit 1;
  if v_private is null then raise exception 'VAPID private key missing'; end if;
  return jsonb_build_object(
    'vapidPublicKey',cfg.vapid_public_key,
    'vapidPrivateKey',v_private,
    'vapidSubject',cfg.vapid_subject
  );
end;
$$;
revoke all on function public.notification_push_server_secrets(text) from public, anon, authenticated;
grant execute on function public.notification_push_server_secrets(text) to service_role;

create or replace function public.dispatch_push_notifications()
returns bigint
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare cfg public.notification_server_config%rowtype; v_secret text; v_request_id bigint;
begin
  select * into cfg from public.notification_server_config where singleton=true;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name='gazalbide_push_dispatch' order by created_at desc limit 1;
  if cfg.edge_function_url is null or v_secret is null then return null; end if;

  select net.http_post(
    url := cfg.edge_function_url,
    headers := jsonb_build_object('Content-Type','application/json','x-dispatch-key',v_secret),
    body := '{"limit":100}'::jsonb,
    timeout_milliseconds := 10000
  ) into v_request_id;
  return v_request_id;
end;
$$;
revoke all on function public.dispatch_push_notifications() from public, anon, authenticated;

-- Keep recent notification history without unbounded growth.
create or replace function public.cleanup_push_notifications()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.notification_outbox
  where created_at < now()-interval '90 days' and status in ('sent','skipped','failed');
$$;
revoke all on function public.cleanup_push_notifications() from public, anon, authenticated;
